mobile_manipulator_mock:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: mico_joint_1
    pid: {p: 10000.0, i: 100000000.0, d: 0.0}
  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: mico_joint_2
    pid: {p: 10000.0, i: 0.0, d: 0.0}
  joint3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: mico_joint_3
    pid: {p: 10000.0, i: 0.0, d: 0.0}
  joint4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: mico_joint_4
    pid: {p: 10000.0, i: 0.0, d: 0.0}
  joint5_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: mico_joint_5
    pid: {p: 10000.0, i: 0.0, d: 0.0}
  joint6_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: mico_joint_6
    pid: {p: 10000.0, i: 0.0, d: 0.0}



